### ISSUE TITLE
Cannot match display.run behaviour with asyncio

### ISSUE THREAD

**Issue by m-col** [flacjacket/pywayland#19]
I'm having some trouble getting some events to dispatch correctly when using Qtile's asyncio event loop for that PR, though everything works fine when using `display.run()` instead. This seems similar to https://github.com/flacjacket/pywayland/issues/16 where flushing the display solved the issue, but on the server-side Display implementation there is no equivalent. Looking at the [original C implementation](https://github.com/wayland-project/wayland/blob/master/src/wayland-server.c#L1358-L1366) the only difference appears to be the use of `wl_display_flush_clients`, which is consistent with flushing lead. Is it simple to add this function to pywayland's lib?

**Comment by m-col** [comment]
Is `_ffi.c` auto-generated?

**Comment by m-col** [comment]
Oh, it is, I was just running `ffi_build.py` from within a nested folder and it was outputting from the wrong place. OK, think i got it...

**Comment by flacjacket** [comment]
Fixed by #20
