### ISSUE TITLE
Build wheel for pypy3.10

### ISSUE THREAD

**Issue by elParaguayo** [flacjacket/pywayland#49]
I'm investigating an issue with the qtile CI test suite where we're getting a segfault on pypy3.9. I tried bumping pypy to 3.10 but this fails to install because there isn't a wheel for pywayland (we install `pywlroots` as a build dependency so we can build our wayland backend code in our wheels).

Could you add this to your release workflow and bump the version? It may not solve our issue but it can't hurt to try!

**Comment by elParaguayo** [comment]
Thanks. Should have thought about this in advance but same issue now with pywlroots ;)

**Comment by flacjacket** [comment]
Done! I created the pywlroots PR to do that, but didn't wrap up that release, but that should be published now!

**Comment by elParaguayo** [comment]
Thanks. Qtile now installs correctly on 3.10 but pytest still segfaulting!
