### ISSUE TITLE
Cannot bind zwlr_foreign_toplevel_manager_v1 protocol

### ISSUE THREAD

**Issue by chrisjbillington** [flacjacket/pywayland#8]
I'm trying to use the [wlroots foreign toplevel management protocol](https://github.com/swaywm/wlroots/blob/master/protocol/wlr-foreign-toplevel-management-unstable-v1.xml), and have managed to get pywayland to generate submodules from the xml file and install them.

However, I can't seem to bind the 'zwlr_foreign_toplevel_manager_v1' interface. I'm not sure if I'm doing something super-naive, as I'm mostly copying off examples for now, as this is my first foray into wayland. But I can bind other interfaces, and zwlr_foreign_toplevel_manager_v1 is very new, so I suppose it's possible that pywayland and zwlr_foreign_toplevel_manager_v1 might not play well with each other quite yet.

Here's what I'm trying:

```python
import sys
from pywayland.client import Display
from pywayland.protocol.wlr_foreign_toplevel_management_unstable_v1 import ZwlrForeignToplevelManagerV1

display = Display()
display.connect()
registry = display.get_registry()

foreign_toplevel_manager = None

def registry_global_handler(registry, id_, interface, version):
    global foreign_toplevel_manager
    if interface == 'zwlr_foreign_toplevel_manager_v1':
        foreign_toplevel_manager = registry.bind(id_, ZwlrForeignToplevelManagerV1, version)
        print("Got zwlr_foreign_toplevel_manager")

registry.dispatcher['global'] = registry_global_handler
display.dispatch()
display.roundtrip()
```

This results in:
```
$ python -i 206.py
Got zwlr_foreign_toplevel_manager
From cffi callback <function dispatcher_func at 0x7f2d64dd1bf8>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pywayland/dispatcher.py", line 35, in dispatcher_func
    args = dispatcher.messages[opcode].c_to_arguments(c_args)
  File "/usr/local/lib/python3.7/site-packages/pywayland/message.py", line 106, in c_to_arguments
    args.append(iface.proxy_class(args_ptr.o))
  File "/usr/local/lib/python3.7/site-packages/pywayland/client/proxy.py", line 47, in __init__
    raise ValueError("Non-Display Proxy objects must be associated to a Display")
ValueError: Non-Display Proxy objects must be associated to a Display
```

If I hackily go into proxy.py and inject my display object rather than raising the exception with
```python
if display is None:
    import __main__
    self._display = __main__.display
```
then I get cffi detecting a garbage pointer:
```
Fatal Python error: ffi.from_handle() detected that the address passed points to garbage. If it is really the result of ffi.new_handle(), then the Python object has already been garbage collected

Current thread 0x00007f750bb4e740 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/pywayland/dispatcher.py", line 31 in dispatcher_func
  File "/usr/local/lib/python3.7/site-packages/pywayland/client/display.py", line 278 in roundtrip
  File "/usr/local/lib/python3.7/site-packages/pywayland/utils.py", line 28 in wrapper
  File "206.py", line 19 in <module>
Aborted (core dumped)
```
So it's clearly not *just* that the proxy object needs a reference to the display.

**Comment by flacjacket** [comment]
This should be fixed now, a much belated thanks for the report. Let me know if you have any additional problems with the current version.

**Comment by chrisjbillington** [comment]
Thanks! I started making my own Cython-based wayland bindings in the meantime, but never completed the project, so I'll give yours a shot again!

**Comment by flacjacket** [comment]
Let me know if you run into any addition issues, happy to help make sure things work!

**Comment by Arnaudv6** [comment]
> [...] and have managed to get pywayland to generate submodules from the xml file and install them.  

just how, please, @chrisjbillington?  
I tried `python3 -m pywayland.scanner --with-protocols` which works, but don't include relevant file,  
and `python3 -m pywayland.scanner -i /tmp/wlroots-master/protocol/*.xml` which throws an exception `KeyError: 'wl_seat'`.

**Comment by chrisjbillington** [comment]
Sorry @Arnaudv6, I don't remember. Perhaps someone else here can describe the correct process.

**Comment by Arnaudv6** [comment]
thanks @chrisjbillington  
@flacjacket any hint please?

**Comment by edrex** [comment]
For client script developers, it would be great to have a low-friction way to interact with the various non-core wayland protocols, An example python package that generates bindings from a local copy during the build.

maybe a package or several with pre-generated bindings for common protocols.

**Comment by RedBearAK** [comment]
> ```shell
> # Use subfolder ("protocols") for relative auto-generated imports to work properly
> python3 -m pywayland.scanner \
>     -i /usr/share/wayland/wayland.xml wlr-foreign-toplevel-management-unstable-v1.xml -o protocols
> 
> # Output:
> INFO:__main__:Parsed 2 input xml files
> INFO:__main__:Generated protocol: wayland
> INFO:__main__:Generated protocol: wlr_foreign_toplevel_management_unstable_v1
> 
> # Usage:
> from protocols.wlr_foreign_toplevel_management_unstable_v1 import ZwlrForeignToplevelManagerV1
> ```

@and3rson 

This also worked for me, as far as generating the protocol files. Cleared up some major confusion I was having. 

But is there any chance you can share some code where you actually got the protocol to work? I made a longer comment describing my problems trying to use the protocol, over on issue #24 (which is still and open issue, as of right now).
