### ISSUE TITLE
cannot import name 'Compositor' error in example

### ISSUE THREAD

**Issue by X52p** [flacjacket/pywayland#9]
I installed pywayland via pip.
When i try to run examples/surface.py I get the following Error:
```
Traceback (most recent call last):
  File "way.py", line 29, in <module>
    from pywayland.protocol.wayland import Compositor, Shell, Shm  # noqa
ImportError: cannot import name 'Compositor' from 'pywayland.protocol.wayland' (/usr/lib/python3.7/site-packages/pywayland/protocol/wayland/__init__.py)
```

am I missing some librarys?

**Comment by flacjacket** [comment]
Thanks for the report! I changed how the names of the generated classes are
created and didn't update the example, eg WlShell rather than Shell. I can
take a look at it tonight, but feel free to submit a pr if you get it
working.

**Comment by phwelo** [comment]
I completed what I believe were the changes mentioned here, but still can't get either example to work. If you're down to troubleshoot I submitted a PR. I wasn't terribly surprised that the `simple-touch.py` example didn't work since i've got nothing touch-able on my laptop and maybe it would assume that?
```
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
global
WL_SHM_FORMAT_ARGB32 not available
Traceback (most recent call last):
  File "./simple-touch.py", line 175, in <module>
    main()
  File "./simple-touch.py", line 168, in main
    while touch['display'].dispatch() != -1:
TypeError: 'NoneType' object is not subscriptable
```
the surface.py example the following:
```
connected to display
got shm
got compositor
Traceback (most recent call last):
  File "./surface.py", line 165, in <module>
    main()
  File "./surface.py", line 138, in main
    raise RuntimeError('no shell found')
RuntimeError: no shell found
```

https://github.com/flacjacket/pywayland/pull/10

**Comment by flacjacket** [comment]
The changes between @phwelo and me seem to get these examples working again on master. Feel free to re-open if you have any additional problems!
